### ISSUE TITLE
Error with macro MOVE_TO_ORIGIN_KTAMV

### ISSUE THREAD

**Issue by joseph-greiner** [TypQxQ/kTAMV#6]
The macro MOVE_TO_ORIGIN_KTAMV gives the error: Unknown command:"KTAMV_MOVE_TO_ORIGIN" when run.
![image](https://github.com/TypQxQ/kTAMV/assets/11715110/9a0f490f-d2a0-4389-a369-e9d2bbeb6d03)

Nothing else happens, please let me know if I can get you more information. (klipper logs etc..)

**Comment by TypQxQ** [comment]
Thank you for finding this. Fixed now. 😃
