### ISSUE TITLE
doesn't correctly recognize the nozzle center

### ISSUE THREAD

**Issue by seene** [TypQxQ/kTAMV#8]
Hey,

I've spent quite some time with the automatic calibration, but unfortunately, it fails for me very often, almost always.
It seems like it doesn't correctly recognize the nozzle center. 

The software identifies all sorts of things as the nozzle center or a circle. I've tried many things already. 
![image1](https://github.com/TypQxQ/kTAMV/assets/9308068/09efe485-f24f-4bd6-a099-72c5459efd99)
![image2](https://github.com/TypQxQ/kTAMV/assets/9308068/9fc160eb-5725-4b0c-824f-df0513ddc3f7)
![image3](https://github.com/TypQxQ/kTAMV/assets/9308068/4d228a7f-891b-483f-8969-74d8d74ae7fe)

The image quality is good
the nozzle is very clean
I've tried getting closer and moving further away
and I've tested various lighting conditions extensively, but unfortunately, without success.

Is there something I might be overlooking?

**Comment by TypQxQ** [comment]
From the images you provide, only the 5th is a good image. 
The other ones are too skewed. The circle of the nozzle hole isn't quite round there.
The 5th image should work...

Lightning conditions are important for OpenCV. Both direct and indirect lightning.
Both the lightning directed from the camera, microscope or endoscope light and the general lightning in the room.
You can try to diffuse the light with some semitransparent white paper, electrical tape or a white sock. :D

When it finds more than one circle, it will pick the one nearest to the middle.

Hope it helps.

**Comment by seene** [comment]
Okay, good to know, thank you. I'll try to improve the camera's mounting. 

In general, is it better to have the camera closer to the nozzle?

**Comment by TypQxQ** [comment]
Yes, in general closer to the nozzle and less reflections, dimmer light.
