### ISSUE TITLE
Have you looked at integrating with Ember Prototypes CXC?

### ISSUE THREAD

**Issue by Drizzt321** [TypQxQ/kTAMV#9]
So Ember Prototypes has a nifty USB webcam with lights, which seems tailor made for this application with short focus length https://www.emberprototypes.com/products/cxc

I'm going to (eventually) see if I can add another motor or something and swing this out into a known location, in order to automate XY tool head offset, and in doing some searches, found this project. Seems like you pretty much have the software side done for this, with this project.

Question though, it looks like all the ML/Compute happens off the Mainsail host? So on a CB1/CM4 on BigTree Manta, I'd still need another system setup elsewhere on the network to host the heavy lifting?

**Comment by TypQxQ** [comment]
kTAMV should work with CXC just as any other webcam.
With CXC, a Z distance of 48mm should be a good starting point.

The Server part of kTAMV runs perfectly fine on the same RaspberryPi as Mainsail and Klipper.
It can run on another computer as well, but I run it on the same Pi4. Not tested on anything slower than a Pi4.
It runs in a separate process to Klipper for better utilization of multiprocessing.

**Comment by TypQxQ** [comment]
There is a thread about TAMV in the Jubilee Discord with a discution on CXC that might help you:
https://discord.com/channels/627982902738681876/675630412399247360/1217355620773269534
